version: 2
jobs:
  unit_test:
    docker:
      - image: circleci/php:7.2
    steps:
      - run:
          name: Unit Test
          command: echo "Going to run Unit Test"
  deploy_to_dev:
    docker:
      - image: circleci/php:7.2
    steps:
      - run:
          name: Deploy to Dev
          command: echo "Going to deploy to dev"

workflows:
  version: 2
  sample_pipeline:
    jobs:
      - unit_test
      - deploy_to_dev